export const FETCH_PAKET = "PAKET/FETCH";
export const PAKET_LOADING = "PAKET/LOADING";
export const CHANGE_SECTION = "SECTION/CHANGE";
export const CHANGE_PAGE = "PAGE/CHANGE";
export const CHANGE_ISLOGIN = "ISLOGIN/CHANGE";
